#define T_to                    0x80
#define T_step                  0x81
#define T_next                  0x82
#define T_wend                  0x83
#define T_until                 0x84
#define T_dim                   0x85
#define T_poke                  0x86
#define T_doke                  0x87
#define T_loke                  0x88
#define T_read                  0x89
#define T_rem                   0x8a
#define T_return                0x8b
#define T_pop                   0x8c
#define T_resumenext            0x8d
#define T_resume                0x8e
#define T_onerror               0x8f
#define T_screencopy            0x90
#define T_swap                  0x91
#define T_plot                  0x92
#define T_pie                   0x93
#define T_draw                  0x94
#define T_polyline              0x95
#define T_polymark              0x96
#define T_unimplmented          0x97
#define T_goto                  0x98
#define T_gosub                 0x99
#define T_then                  0x9a
#define T_else                  0x9b
#define T_restore               0x9c
#define T_for                   0x9d
#define T_while                 0x9e
#define T_repeat                0x9f
#define T_extinst               0xa0
#define T_print                 0xa1
#define T_if                    0xa2
#define T_update                0xa3
#define T_sprite                0xa4
#define T_freeze                0xa5
#define T_off                   0xa6
#define T_on                    0xa7
#define T_extensioninst         0xa8
#define T_locate                0xa9
#define T_paper                 0xaa
#define T_pen                   0xab
#define T_home                  0xac
#define T_sizeb                 0xad
#define T_sizew                 0xae
#define T_sizel                 0xaf
#define T_cup                   0xb0
#define T_cdown                 0xb1
#define T_cleft                 0xb2
#define T_cright                0xb3
#define T_cls                   0xb4
#define T_inc                   0xb5
#define T_dec                   0xb6
#define T_screenswap            0xb7
#define T_extfunc               0xb8
#define T_psg                   0xb9
#define T_scrn                  0xba
#define T_dreg                  0xbb
#define T_areg                  0xbc
#define T_point                 0xbd
#define T_drivestr              0xbe
#define T_dirstr                0xbf
#define T_extensionfunc         0xc0
#define T_abs                   0xc1
#define T_colour                0xc2
#define T_fkey                  0xc3
#define T_sin                   0xc4
#define T_cos                   0xc5
#define T_drive                 0xc6
#define T_timer                 0xc7
#define T_logic                 0xc8
#define T_fn                    0xc9
#define T_not                   0xca
#define T_rnd                   0xcb
#define T_val                   0xcc
#define T_asc                   0xcd
#define T_chr                   0xce
#define T_inkey                 0xcf
#define T_scancode              0xd0
#define T_mid                   0xd1
#define T_right                 0xd2
#define T_left                  0xd3
#define T_length                0xd4
#define T_start                 0xd5
#define T_len                   0xd6
#define T_pi                    0xd7
#define T_peek                  0xd8
#define T_deek                  0xd9
#define t_leek                  0xda
#define T_zone                  0xdb
#define T_xsprite               0xdc
#define T_ysprite               0xdd
#define T_xmouse                0xde
#define T_ymouse                0xdf
#define T_mousekey              0xe0
#define T_physic                0xe1
#define T_back                  0xe2
#define T_log                   0xe3
#define T_pof                   0xe4
#define T_mode                  0xe5
#define T_time                  0xe6
#define T_date                  0xe7
#define T_screen                0xe8
#define T_default               0xe9
#define T_operator              0xea
#define T_xor                   0xeb
#define T_or                    0xec
#define T_and                   0xed
#define T_neq                   0xee
#define T_leq                   0xef
#define T_geq                   0xf0
#define T_eq                    0xf1
#define T_lt                    0xf2
#define T_gt                    0xf3
#define T_add                   0xf4
#define T_sub                   0xf5
#define T_mod                   0xf6
#define T_mul                   0xf7
#define T_div                   0xf8
#define T_pow                   0xf9
#define T_var                   0xfa
#define T_constbin              0xfb
#define T_conststr              0xfc
#define T_consthex              0xfd
#define T_constint              0xfe
#define T_constflt              0xff

#define T_operand               0xb8


/*
 * extended functions ($b8)
 */
#define T_extf_sinh             0x80
#define T_extf_cosh             0x81
#define T_extf_tanh             0x82
#define T_extf_asin             0x83
#define T_extf_acos             0x84
#define T_extf_atan             0x85
#define T_extf_upper            0x86
#define T_extf_lower            0x87
#define T_extf_current          0x88
#define T_extf_match            0x89
#define T_extf_errn             0x8a
#define T_extf_errl             0x8b
#define T_extf_varptr           0x8c
#define T_extf_input            0x8d
#define T_extf_flip             0x8e
#define T_extf_free             0x8f
#define T_extf_str              0x90
#define T_extf_hex              0x91
#define T_extf_bin              0x92
#define T_extf_string           0x93
#define T_extf_space            0x94
#define T_extf_instr            0x95
#define T_extf_max              0x96
#define T_extf_min              0x97
#define T_extf_lof              0x98
#define T_extf_eof              0x99
#define T_extf_dirfirst         0x9a
#define T_extf_dirnext          0x9b
#define T_extf_btst             0x9c
#define T_extf_collide          0x9d
#define T_extf_accnb            0x9e
#define T_extf_language         0x9f
#define T_extf_hunt             0xa1
#define T_extf_true             0xa2
#define T_extf_false            0xa3
#define T_extf_xcurs            0xa4
#define T_extf_ycurs            0xa5
#define T_extf_jup              0xa6
#define T_extf_jleft            0xa7
#define T_extf_jright           0xa8
#define T_extf_jdown            0xa9
#define T_extf_fire             0xaa
#define T_extf_joy              0xab
#define T_extf_movon            0xac
#define T_extf_icon             0xad
#define T_extf_tab              0xae
#define T_extf_exp              0xaf
#define T_extf_charlen          0xb0
#define T_extf_mnbar            0xb1
#define T_extf_mnselect         0xb2
#define T_extf_windon           0xb3
#define T_extf_xtext            0xb4
#define T_extf_ytext            0xb5
#define T_extf_xgraphic         0xb6
#define T_extf_ygraphic         0xb7
#define T_extf_sqr              0xb9
#define T_extf_divx             0xba
#define T_extf_divy             0xbb
#define T_extf_ln               0xbc
#define T_extf_tan              0xbd
#define T_extf_drvmap           0xbe
#define T_extf_fileselect       0xbf
#define T_extf_dfree            0xc0
#define T_extf_sgn              0xc1
#define T_extf_port             0xc2
#define T_extf_pvoice           0xc3
#define T_extf_int              0xc4
#define T_extf_detect           0xc5
#define T_extf_deg              0xc6
#define T_extf_rad              0xc7


/*
 * extended instructions ($a0)
 */
#define T_exti_listbank         0x00
#define T_exti_llistbank        0x01
#define T_exti_follow           0x02
#define T_exti_frequency        0x03
#define T_exti_cont             0x04
#define T_exti_change           0x05
#define T_exti_search           0x06
#define T_exti_delete           0x07
#define T_exti_merge            0x08
#define T_exti_auto             0x09
#define T_exti_new              0x0a
#define T_exti_unnew            0x0b
#define T_exti_fload            0x0c
#define T_exti_fsave            0x0d
#define T_exti_reset            0x0e
#define T_exti_system           0x0f
#define T_exti_env              0x10
#define T_exti_renum            0x11
#define T_exti_multi            0x12
#define T_exti_full             0x13
#define T_exti_grab             0x14
#define T_exti_list             0x15
#define T_exti_llist            0x16
#define T_exti_hexa             0x17
/* 0x18 unused */
#define T_exti_accload          0x19
#define T_exti_accnew           0x1a
#define T_exti_lower            0x1b
#define T_exti_upper            0x1c
#define T_exti_english          0x1d
#define T_exti_francais         0x1e

#define T_exti_dirw             0x70
#define T_exti_fade             0x71
#define T_exti_bcopy            0x72
#define T_exti_square           0x73
#define T_exti_previous         0x74
#define T_exti_transpose        0x75
#define T_exti_shift            0x76
#define T_exti_waitkey          0x77
#define T_exti_dir              0x78
#define T_exti_ldir             0x79
#define T_exti_bload            0x7a
#define T_exti_bsave            0x7b
#define T_exti_qwindow          0x7c
#define T_exti_asset            0x7d
#define T_exti_charcopy         0x7e
#define T_exti_under            0x7f
#define T_exti_menustr          0x80
#define T_exti_menu             0x81
#define T_exti_title            0x82
#define T_exti_border           0x83
#define T_exti_hardcopy         0x84
#define T_exti_windcopy         0x85
#define T_exti_redraw           0x86
#define T_exti_centre           0x87
#define T_exti_tempo            0x88
#define T_exti_volume           0x89
#define T_exti_envel            0x8a
#define T_exti_boom             0x8b
#define T_exti_shoot            0x8c
#define T_exti_bell             0x8d
#define T_exti_play             0x8e
#define T_exti_noise            0x8f
#define T_exti_voice            0x90
#define T_exti_music            0x91
#define T_exti_box              0x92
#define T_exti_rbox             0x93
#define T_exti_bar              0x94
#define T_exti_rbar             0x95
#define T_exti_appear           0x96
#define T_exti_bclr             0x97
#define T_exti_bset             0x98
#define T_exti_rol              0x99
#define T_exti_ror              0x9a
#define T_exti_curs             0x9b
#define T_exti_clw              0x9c
#define T_exti_bchg             0x9d
#define T_exti_call             0x9e
#define T_exti_trap             0x9f
#define T_exti_run              0xa1
#define T_exti_clearkey         0xa2
#define T_exti_lineinput        0xa3
#define T_exti_input            0xa4
#define T_exti_clear            0xa5
#define T_exti_data             0xa6
#define T_exti_end              0xa7
#define T_exti_erase            0xa8
#define T_exti_reserve          0xa9
#define T_exti_asdatascreen     0xaa
#define T_exti_aswork           0xab
#define T_exti_asscreen         0xac
#define T_exti_asdata           0xad
#define T_exti_copy             0xae
#define T_exti_def              0xaf
#define T_exti_hide             0xb0
#define T_exti_show             0xb1
#define T_exti_changemouse      0xb2
#define T_exti_limitmouse       0xb3
#define T_exti_movex            0xb4
#define T_exti_movey            0xb5
#define T_exti_fix              0xb6
#define T_exti_bgrab            0xb7
#define T_exti_fill             0xb9
#define T_exti_keylist          0xba
#define T_exti_keyspeed         0xbb
#define T_exti_move             0xbc
#define T_exti_anim             0xbd
#define T_exti_unfreeze         0xbe
#define T_exti_setzone          0xbf
#define T_exti_resetzone        0xc0
#define T_exti_limitsprite      0xc1
#define T_exti_priority         0xc2
#define T_exti_reduce           0xc3
#define T_exti_putsprite        0xc4
#define T_exti_getsprite        0xc5
#define T_exti_load             0xc6
#define T_exti_save             0xc7
#define T_exti_palette          0xc8
#define T_exti_synchro          0xc9
#define T_exti_error            0xca
#define T_exti_break            0xcb
#define T_exti_let              0xcc
#define T_exti_key              0xcd
#define T_exti_openin           0xce
#define T_exti_openout          0xcf
#define T_exti_open             0xd0
#define T_exti_close            0xd1
#define T_exti_field            0xd2
#define T_exti_as               0xd3
#define T_exti_putkey           0xd4
#define T_exti_getpalette       0xd5
#define T_exti_kill             0xd6
#define T_exti_rename           0xd7
#define T_exti_rmdir            0xd8
#define T_exti_mkdir            0xd9
#define T_exti_stop             0xda
#define T_exti_waitvbl          0xdb
#define T_exti_sort             0xdc
#define T_exti_get              0xdd
#define T_exti_flash            0xde
#define T_exti_using            0xdf
#define T_exti_lprint           0xe0
#define T_exti_autoback         0xe1
#define T_exti_setline          0xe2
#define T_exti_grwriting        0xe3
#define T_exti_setmark          0xe4
#define T_exti_setpaint         0xe5
/* *0xe6 unused */
#define T_exti_setpattern       0xe7
#define T_exti_clip             0xe8
#define T_exti_arc              0xe9
#define T_exti_polygon          0xea
#define T_exti_circle           0xeb
#define T_exti_earc             0xec
#define T_exti_epie             0xed
#define T_exti_ellipse          0xee
#define T_exti_writing          0xef
#define T_exti_paint            0xf0
#define T_exti_ink              0xf1
#define T_exti_wait             0xf2
#define T_exti_click            0xf3
#define T_exti_put              0xf4
#define T_exti_zoom             0xf5
#define T_exti_setcurs          0xf6
#define T_exti_scrolldown       0xf7
#define T_exti_scrollup         0xf8
#define T_exti_scroll           0xf9
#define T_exti_inverse          0xfa
#define T_exti_shade            0xfb
#define T_exti_windopen         0xfc
#define T_exti_window           0xfd
#define T_exti_windmove         0xfe
#define T_exti_windel           0xff
