/*
 * bank 1: sprites (permanent)
 * bank 2: icons (permanent)
 * bank 3: music (permanent)
 * bank 4: 3d (permanent)
 * bank 15: menu (temporary)
 * charset: 1-15 (permanent)
 * screen: 1-15 (temporary)
 * datascreen: 1-15 (permanent)
 * work: 1-15 (temporary)
 * data: 1-15 (permanent)
 * code: 1-15 (varies)
 */
bank_data       = $81
bank_datascreen = $82
bank_program    = $83
bank_font       = $84
