*
* Float function numbers (trap #6)
*
F_add         = 0
F_sub         = 1
F_mul         = 2
F_div         = 3
F_sin         = 4
F_cos         = 5
F_tan         = 6
F_exp         = 7
F_ln          = 8
F_log         = 9
F_sqr         = 10
F_atof        = 11
F_ftoa        = 12
F_ftol        = 13
F_ltof        = 14
F_eq          = 15
F_ne          = 16
F_gt          = 17
F_ge          = 18
F_lt          = 19
F_le          = 20
F_asin        = 21
F_acos        = 22
F_atan        = 23
F_sinh        = 24
F_cosh        = 25
F_tanh        = 26
F_int         = 27
F_pow         = 28
F_abs         = 29

F_inv         = $ff00+0
F_getsgn      = $ff00+1
F_pi          = $ff00+2
F_deg         = $ff00+3
F_rad         = $ff00+4
F_zero        = $ff00+5

