*
* Music function numbers (trap #7)
*

M_initsound    = 0
M_startmusic   = 1
M_stopvoice    = 2
M_restartvoice = 3
M_freeze       = 4
M_unfreeze     = 5
M_tempo        = 6
M_startinter   = 7
M_stopinter    = 8
M_transpose    = 9
M_voicepos     = 10
*
* added by falcon extension
*
M_trackerinit        = 11
M_soundreset         = 12
M_trackerplay        = 13
M_trackerloop        = 14
M_trackerffwd        = 15
M_trackerpause       = 16
M_trackerstop        = 17
M_trackerspeed       = 18
M_trackersongpos     = 19
M_trackerpattpos     = 20
M_trackervu          = 21
M_trackerspectrum    = 22
M_trackersongprev    = 23
M_trackersongnext    = 24
M_trackerstatus      = 25
M_trackerscopedraw   = 26
M_trackerscopeundraw = 27
M_trackerpattinfo    = 28
M_trackertempo       = 29
