*
* Sprite function numbers (trap #5)
*
S_initmode        = 0
S_chgbank         = 1
S_chglimit        = 2
S_synchro         = 3
S_priority        = 4
S_collide         = 5
S_posprite        = 6
S_spritesonoff    = 7
S_spritenonoff    = 8
S_sprite          = 9
S_movesonoff      = 10
S_movenonoff      = 11
S_moveinit        = 12
S_animsonoff      = 13
S_animnonoff      = 14
S_animinit        = 15
S_actualise       = 16
S_show            = 17
S_hide            = 18
S_chgmouse        = 19
S_mouse           = 20
S_mousekey        = 21
S_screentoback    = 22
S_backtoscreen    = 23
S_drawmouse       = 24
S_setzone         = 25
S_zone            = 26
S_chgscreen       = 27
S_stopmouse       = 28
S_drawsprites     = 29
S_startinter      = 30
S_stopinter       = 31
S_limitmouse      = 32
S_scrcopy         = 33
S_puticon         = 34
S_putsprite       = 35
S_initzones       = 36
S_getsprite       = 37
S_reduce          = 38
S_initflash       = 39
S_flash           = 40
S_restartmouse    = 41
S_zoom            = 42
S_appear          = 43
S_movemouse       = 44
S_moveon          = 45
S_shifton         = 46
S_redraw          = 47
S_intersynconoff  = 48
S_inter           = 49
S_cls             = 50
S_getblock        = 51
S_putblock        = 52
S_fade            = 53
*
* added by falcon extension
*
S_f54             = 54

S_f56             = 56
S_f57             = 57
S_falc_print      = 58

S_multipen_status = 60
S_multipen_off    = 61
S_multipen_on     = 62
S_falc_pen        = 63
S_falc_paper      = 64
S_falc_locate     = 65
S_falc_xcurs      = 66
S_falc_ycurs      = 67
S_stosfont        = 68
S_charwidth       = 69
S_charheight      = 70
S_st_mouse        = 71
S_st_mouse_color  = 72
S_st_mouse_on     = 73
S_st_mouse_off    = 74
S_st_mouse_stat   = 75
S_fileselect      = 76
S_falc_centre     = 77
S_limit_st_mouse  = 78

