*
* Window function numbers (trap #3)
*
W_chrout           = 0
W_prtstring        = 1
W_locate           = 2
W_setpaper         = 3
W_setpen           = 4
W_tstscreen        = 5
W_initwind         = 6
W_stopinter        = 7
W_windon           = 8
W_delwindow        = 9
W_initmode         = 10
W_getbuffer        = 11
W_hardcopy         = 12
W_getcurwindow     = 13
W_fixcursor        = 14
W_startinter       = 15
W_qwindon          = 16
W_coordcurs        = 17
W_centre           = 18
W_setback          = 19
W_autoins          = 20
W_join             = 21
W_smallcursor      = 22
W_largecursor      = 23
W_windmove         = 24
W_currwindow       = 25
W_newicon          = 26
W_actcache         = 27
W_getcharset       = 28
W_setcharset       = 29
W_border           = 30
W_title            = 31
W_autobackon       = 32
W_autobackoff      = 33
W_autobackrest     = 34
W_xgraphic         = 35
W_ygraphic         = 36
W_xtext            = 37
W_ytext            = 38
W_box              = 39
W_update           = 40
*
* added by falcon extension
*
W_fmenu_select     = 41
W_fmenu_item       = 42
W_fmenu_init       = 43
W_fmenu_on         = 44
W_fmenu_kill       = 45
W_fmenu_freeze     = 46
W_fmenustr         = 47
W_fmenustr_off     = 48
W_fmenustr_on      = 49
W_fmenu_check_item = 50
W_fmenu_height     = 51
W_form_alert       = 52

*
* special escape characters
*
C_wordleft         = 1
C_wordright        = 2
C_curleft          = 3
C_scrollht         = 4
C_scrollbs         = 5
C_return           = 6
C_delete           = 7
C_backspace        = 8
C_curright         = 9
C_curdown          = 10
C_curup            = 11
C_clearscreen      = 12
C_linestart        = 13
C_wrtreplace       = 14
C_wrttransparent   = 15
C_wrtxor           = 16
C_curon            = 17
C_normal           = 18
C_shadowoff        = 19
C_curoff           = 20
C_inverse          = 21
C_shadowon         = 22
C_scrollon         = 23
C_clreol           = 24
C_scrolloff        = 25
C_delete           = 26
C_escape           = 27
C_insert           = 28
C_underlineoff     = 29
C_home             = 30
C_underlineon      = 31
